citahub/cita-cli

- README.md
- cita-cli/src/interactive.rs
1. Modify readme
2. Fix save privaty key on history bug
> Modify readme and fix save privaty key on history bug

- cita-cli/src/cli.rs
- cita-cli/src/interactive.rs
- cita-tool/src/client/basic.rs
- cita-tool/src/client/mod.rs
- cita-tool/src/client/system_contract.rs
- cita-tool/src/crypto/cita_ed25519.rs
- cita-tool/src/crypto/cita_secp256k1.rs
- cita-tool/src/lib.rs
- cita-tool/src/protos/mod.rs
1. Fix save private key bug
2. Remove super on tool
> Fix save privakey bug

- README.md
- cita-tool/src/client/basic.rs
- cita-tool/src/client/system_contract.rs
1. Remove unnecessary mutable
2. Fix address encode
3. Readme add compile the Linux cross-platform version
> Remove unnecessary mutable

- cita-cli/src/cli.rs
- cita-tool/src/client/basic.rs
1. Id change to atomic
2. Transfer function to trait
3. Fix typo
> Id change to atomic

- cita-cli/src/cli.rs
- cita-tool/src/client/system_contract.rs
- cita-tool/src/lib.rs
* Authorization
* Role
* RoleManagement
* Permission
* PermissionManagement
> Add more system contracts support

- cita-cli/src/cli.rs
- cita-cli/src/interactive.rs
- cita-cli/src/main.rs
1. Fix remove private key bug
2. Add search command
3. Change complete to Arc
> Fix remove private key bug

- README.md
- cita-cli/src/interactive.rs
Hope this is the last time to fix it...
> Fix save private key

- Cargo.toml
- cita-cli/src/cli.rs
- cita-tool/Cargo.toml
- cita-tool/src/client/system_contract.rs
- cita-tool/src/lib.rs
- tool-derive/Cargo.toml
- tool-derive/src/lib.rs
> Change to use proc macro

- cita-cli/src/cli.rs
- cita-tool/src/client/basic.rs
- cita-tool/src/client/system_contract.rs
- tool-derive/src/lib.rs
1. Add system contract quota params
2. Add amend get h256 value interface
3. Change tokio runtime to muli-thread
4. Proc macro add some check
5. Use `Box<dyn Trait>` install of `Box<Trait>`
> Lots of update

- cita-cli/src/cli.rs
- cita-cli/src/interactive.rs
- cita-cli/src/main.rs
- cita-tool/src/client/basic.rs
- cita-tool/src/lib.rs
1. Separate the generated signature transaction into two functions
2. Add tx interface
> Add tx interface

- cita-cli/src/cli.rs
- cita-cli/src/interactive.rs
- cita-cli/src/main.rs
- cita-tool/src/abi.rs
- cita-tool/src/lib.rs
Add decode log and function interface
> Add decode log and function interface

- cita-cli/src/cli.rs
- cita-tool/src/client/basic.rs
- cita-tool/src/client/mod.rs
- cita-tool/src/client/system_contract.rs
- cita-tool/src/lib.rs
- cita-tool/src/rpctypes.rs
- tool-derive/src/lib.rs
1. Refactor client
2. Update system contract address
> Refactor client

- README.md
- cita-cli/src/cli.rs
- cita-cli/src/interactive.rs
- cita-tool/src/client/basic.rs
- cita-tool/src/client/mod.rs
- cita-tool/src/client/system_contract.rs
- cita-tool/src/client/transaction_option.rs
- cita-tool/src/lib.rs
- tool-derive/src/lib.rs
1. Change send transaction api, use transaction option
2. Remove `newNode` funciton
> Change send transaction api, use transaction option

- cita-cli/src/cli.rs
- cita-tool/src/crypto/cita_ed25519.rs
- cita-tool/src/crypto/cita_secp256k1.rs
- cita-tool/src/crypto/mod.rs
- cita-tool/src/protos/mod.rs
1. Recover public key
2. Fix command line url bug
> Recover pubkey, fix a bug

- cita-cli/src/cli/other_command.rs
- cita-cli/src/cli/util.rs
1. Modify function `parse_height`
2. Modify benchmark processor
> Some modify

- cita-tool/Cargo.toml
- cita-tool/src/crypto/crypto_trait.rs
- cita-tool/src/lib.rs
> replace sha3 to tiny-keccak

- .travis.yml
- cita-cli/src/cli/abi_command.rs
- cita-cli/src/cli/contract_command.rs
- cita-cli/src/cli/tx_command.rs
- cita-tool/src/client/basic.rs
- cita-tool/src/client/system_contract.rs
- cita-tool/src/crypto/cita_secp256k1.rs
- cita-tool/src/crypto/mod.rs
> add some useful subcommand

- cita-cli/src/cli/mod.rs
- cita-cli/src/cli/other_command.rs
- cita-cli/src/cli/rpc_command.rs
- cita-cli/src/cli/tx_command.rs
- cita-cli/src/cli/util.rs
- cita-tool/src/client/basic.rs
- cita-tool/src/client/transaction_option.rs
- cita-tool/src/lib.rs
- cita-tool/src/protos/mod.rs
> Value must u256

- README.md
- cita-cli/src/cli/contract_command.rs
- cita-tool/src/client/system_contract.rs
> add node manage method

- cita-cli/src/cli/abi_command.rs
- cita-cli/src/cli/amend_command.rs
- cita-cli/src/cli/contract_command.rs
- cita-cli/src/cli/other_command.rs
- cita-cli/src/cli/rpc_command.rs
- cita-cli/src/cli/store_command.rs
- cita-cli/src/cli/tx_command.rs
- cita-cli/src/interactive.rs
- cita-cli/src/json_color.rs
- cita-cli/src/main.rs
- cita-tool/src/abi.rs
- cita-tool/src/client/basic.rs
- cita-tool/src/crypto/cita_secp256k1.rs
- cita-tool/src/crypto/mod.rs
- cita-tool/src/error.rs
- cita-tool/src/protos/mod.rs
Made some changes in accordance with clippy
> Made some changes in accordance with clippy

- cita-cli/src/cli/amend_command.rs
- cita-cli/src/cli/rpc_command.rs
- cita-cli/src/cli/store_command.rs
- cita-cli/src/cli/tx_command.rs
> Fix quota analysis

- .travis.yml
- cita-cli/Cargo.toml
- cita-cli/src/cli/key_command.rs
- cita-cli/src/cli/mod.rs
- cita-cli/src/cli/other_command.rs
- cita-cli/src/cli/rpc_command.rs
- cita-cli/src/cli/tx_command.rs
- cita-cli/src/cli/util.rs
- cita-cli/src/interactive.rs
- cita-cli/src/main.rs
- cita-cli/src/printer.rs
- cita-tool/src/abi.rs
- cita-tool/src/client/basic.rs
- cita-tool/src/client/transaction_option.rs
- cita-tool/src/crypto/cita_secp256k1.rs
- cita-tool/src/crypto/mod.rs
- cita-tool/src/lib.rs
- cita-tool/src/protos/mod.rs
- cita-tool/src/rpctypes.rs
- tool-derive/src/lib.rs
fix #38  and small optimization
> Small optimization

- cita-cli/src/cli/amend_command.rs
- cita-cli/src/cli/contract_command.rs
- cita-tool/src/client/basic.rs
Modify amend kv command, support muil-kv
> Modify amend kv

- cita-cli/src/cli/contract_command.rs
- cita-tool/src/client/system_contract.rs
- tool-derive/src/lib.rs
add system contract call height param
> add system contract call height param

- tool-derive/src/lib.rs
> Fix panic on scm

- cita-cli/src/cli/amend_command.rs
- cita-cli/src/cli/contract_command.rs
- cita-cli/src/cli/mod.rs
- cita-cli/src/cli/other_command.rs
- cita-cli/src/cli/rpc_command.rs
- cita-cli/src/cli/store_command.rs
- cita-cli/src/cli/tx_command.rs
- cita-cli/src/cli/util.rs
- cita-cli/src/printer.rs
- cita-tool/src/client/basic.rs
- cita-tool/src/crypto/mod.rs
- cita-tool/src/lib.rs
1. Change default quota used to 10_000_000
2. Add address validity verification
> Change default quota used to 10_000_000

- cita-cli/src/cli/amend_command.rs
- cita-cli/src/cli/mod.rs
- cita-cli/src/cli/rpc_command.rs
- cita-cli/src/cli/util.rs
- cita-tool/src/client/basic.rs
> Add new rpc interface

- cita-cli/Cargo.toml
- cita-cli/src/cli/amend_command.rs
- cita-cli/src/cli/contract_command.rs
- cita-cli/src/cli/mod.rs
- cita-cli/src/cli/other_command.rs
- cita-cli/src/cli/rpc_command.rs
- cita-cli/src/cli/store_command.rs
- cita-cli/src/cli/tx_command.rs
- cita-cli/src/interactive.rs
- cita-cli/src/main.rs
- cita-tool/src/rpctypes.rs
1. Add the ability to set environment variables in interactive mode
2. The latest transaction hash will exist in the `tx-hash` variable
3. Search command doesn‘t case sensitive
> Add the ability to set environment variables in interactive mode

- .ci-script/clippy_test.sh
- .ci-script/travis-install-libsodium.sh
- .travis.yml
- cita-cli/Cargo.toml
> Open clippy ci check

- cita-cli/Cargo.toml
- cita-cli/src/cli/mod.rs
- cita-cli/src/interactive.rs
1. Support dynamic switching between editing mode(Vi or Emacs) and completion mode(Circular or List). Default Emacs and List
2. Fix garbled characters in `rustyline` mode
3. Tips for adding `ethabi`, `get`, `set` commands
4. Add color for completion
> add some feature

- cita-cli/src/cli/contract_command.rs
- cita-cli/src/interactive.rs
- cita-tool/contract_abi/EmergencyBrake.abi
- cita-tool/src/client/system_contract.rs
1. Add emergency brake contract
> Add emergency brake contract

- cita-cli/src/cli/abi_command.rs
- cita-cli/src/interactive.rs
- cita-tool/src/abi.rs
> Change abi interface

- README.md
- cita-cli/Cargo.toml
- cita-cli/src/cli/amend_command.rs
- cita-cli/src/cli/contract_command.rs
- cita-cli/src/cli/key_command.rs
- cita-cli/src/cli/mod.rs
- cita-cli/src/cli/other_command.rs
- cita-cli/src/cli/rpc_command.rs
- cita-cli/src/cli/store_command.rs
- cita-cli/src/cli/tx_command.rs
- cita-cli/src/cli/util.rs
- cita-cli/src/interactive.rs
- cita-tool/Cargo.toml
- cita-tool/src/abi.rs
- cita-tool/src/client/basic.rs
- cita-tool/src/client/system_contract.rs
- cita-tool/src/crypto/cita_ed25519.rs
- cita-tool/src/crypto/cita_secp256k1.rs
- cita-tool/src/crypto/cita_sm2.rs
- cita-tool/src/crypto/crypto_trait.rs
- cita-tool/src/crypto/mod.rs
- cita-tool/src/lib.rs
- cita-tool/src/protos/mod.rs
- tool-derive/Cargo.toml
- tool-derive/src/lib.rs
> Support the sm2 algorithm

- cita-cli/src/cli/mod.rs
- cita-cli/src/cli/util.rs
> fix address validator for 0x

- cita-cli/src/cli/contract_command.rs
- cita-tool/contract_abi/VersionManager.abi
- cita-tool/src/client/basic.rs
- cita-tool/src/client/system_contract.rs
> Add version contract

- cita-cli/src/cli/mod.rs
- cita-cli/src/cli/other_command.rs
- cita-cli/src/interactive.rs
1. add save private key option
2. transfer quota add to 30000
> add save private key option

- .ci-script/clippy_test.sh
- README.md
- cita-cli/src/cli/abi_command.rs
- cita-tool/Cargo.toml
- cita-tool/src/abi.rs
1. add encode constructor
2. use stable clippy instead of nightly
> add encode constructor

- cita-cli/src/cli/amend_command.rs
- cita-cli/src/cli/mod.rs
- cita-cli/src/cli/other_command.rs
- cita-cli/src/interactive.rs
> fuzzy matching

- README.md
- cita-cli/src/cli/mod.rs
- cita-cli/src/cli/other_command.rs
- cita-cli/src/main.rs
> gen_completion

- cita-cli/src/cli/amend_command.rs
- cita-cli/src/cli/contract_command.rs
- cita-cli/src/cli/other_command.rs
- cita-cli/src/cli/rpc_command.rs
- cita-cli/src/cli/store_command.rs
- cita-cli/src/cli/tx_command.rs
- cita-cli/src/interactive.rs
- cita-cli/src/main.rs
- cita-tool/src/client/basic.rs
- tool-derive/src/lib.rs
> use single event loop

- cita-cli/Cargo.toml
- cita-cli/src/cli/contract_command.rs
- cita-cli/src/cli/key_command.rs
- cita-tool/src/client/system_contract.rs
> fix set version type bug

- cita-cli/src/cli/key_command.rs
- cita-tool/src/abi.rs
- cita-tool/src/client/basic.rs
- cita-tool/src/client/system_contract.rs
- cita-tool/src/crypto/cita_ed25519.rs
- cita-tool/src/crypto/cita_secp256k1.rs
- cita-tool/src/crypto/cita_sm2.rs
- cita-tool/src/crypto/mod.rs
- cita-tool/src/protos/mod.rs
1. Add verify interface
2. Fix `pub-to-address` command
> Add verify interface

- cita-tool/src/lib.rs
- cita-tool/src/protos/mod.rs
> Beautify Transaction decode

- README.md
Update the outdated command usage of switch in the example
> Update the outdated command usage of switch in the example

- cita-tool/Cargo.toml
- cita-tool/src/crypto/cita_secp256k1.rs
Replace `eth-secp256k1` by `secp256k1`
#100
> cita-tool Upgrade Secp256k1

- cita-cli/Cargo.toml
- cita-cli/src/cli.rs
- cita-cli/src/cli/amend_command.rs
- cita-cli/src/cli/contract_command.rs
- cita-cli/src/cli/key_command.rs
- cita-cli/src/cli/other_command.rs
- cita-cli/src/cli/rpc_command.rs
- cita-cli/src/cli/store_command.rs
- cita-cli/src/cli/tx_command.rs
- cita-cli/src/cli/util.rs
- cita-cli/src/interactive.rs
- cita-cli/src/main.rs
- cita-tool/Cargo.toml
- cita-tool/src/crypto.rs
- cita-tool/src/crypto/cita_ed25519.rs
- cita-tool/src/crypto/cita_secp256k1.rs
- cita-tool/src/crypto/crypto_trait.rs
- cita-tool/src/lib.rs
- cita-tool/src/protos.rs
Using `blake2b_simd` and `ed25519-dalek` for signature algorithm.
#101
> cita-tool Switch signature algorithm

- cita-cli/src/cli/rpc_command.rs
- cita-tool/src/client/basic.rs
Support new CITA JSON-RPC interface for cita-cli: peersInfo
#107
> cita-tool cita-cli support JSON-RPC peersInfo

- cita-cli/src/cli/rpc_command.rs
- cita-tool/src/client/basic.rs
Support new CITA JSON-RPC interface for cita-cli: getVersion.
#106
> cita-cli support JSON-RPC getVersion

- README-CN.md
- README.md
- cita-cli/src/cli/abi_command.rs
- cita-cli/src/cli/contract_command.rs
- cita-cli/src/cli/other_command.rs
- cita-cli/src/cli/rpc_command.rs
- cita-cli/src/interactive.rs
- cita-tool/src/client/system_contract.rs
- tool-derive/src/lib.rs
> fix panic on scm group

- cita-tool/src/client/basic.rs
Content-type is required for most http server, such `actix`
> Add Content-Type

- cita-tool/src/client/basic.rs
https://github.com/cryptape/cita/pull/563
> support version 2

- .travis.yml
- cita-cli/Cargo.toml
- cita-cli/src/interactive.rs
- cita-tool/src/client/basic.rs
- cita-tool/src/protos.rs
1. Fix #120 
2. Fix interactive input cap limit https://github.com/kkawakam/rustyline/pull/255
No new version will be released yet
> fix: Fix interactive input cap limit

- cita-cli/src/cli/tx_command.rs
Support content file input for `decode-unverifiedTransaction`.
Example:
```shell
$ cat content.data
0x0ab101122064356565386436313239333634343735396462336265663561323132373366381880ade20420a50b2a2934745248320415874832614378748765108377874876589761413476587168173654659847534896503220000000000000000000000000000000000000000000000000000000000000000040014a14ffffffffffffffffffffffffffffffffff0100005220000000000000000000000000000000000000000000000000000000000000000112415c2b3ee0c4d42e34f64b315273ca043d2b4dd2067317dabb6c5c4c1423032408516e73bf1fcdcfb2a570f3d40f6a1a91c6eaa8cb2745f4b6c2acbc3937dc08e701
$ cita-cli tx decode-unverifiedTransaction --algorithm sm2 --file content.data
{
"crypto": 0,
"signature": "0x5c2b3ee0c4d42e34f64b315273ca043d2b4dd2067317dabb6c5c4c1423032408516e73bf1fcdcfb2a570f3d40f6a1 …
```
> Support content file input for decode-unverifiedTransaction

- cita-cli/Cargo.toml
> bump to 0.19.7

- .travis.yml
- cita-cli/Cargo.toml
- cita-cli/build.rs
- cita-cli/src/interactive.rs
- cita-cli/src/main.rs
- tool-derive/src/lib.rs
> bump to 20.2.0

- cita-tool/src/abi.rs
```
cita> ethabi encode params --param string '[{"constant":false,"inputs":[{"name":"num","type":"uint256"}],"name":"store","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"retreive","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"}]'
"000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000001305b7b22636f6e7374616e74223a66616c73652c22696e70757473223a5b7b226e616d65223a226e756d222c2274797065223a2275696e74323536227d5d2c226e616d65223a2273746f7265222c226f757470757473223a5b5d2c2270617961626c65223a66616c73652c2273746174654d75746162696c697479223a226e6f6e70617961626c65222c2274797065223a2266756e6374696f6e227d2c7b2263 …
```
> Escape string value in json

- cita-cli/Cargo.toml
> bump to 20.2.1

- cita-cli/Cargo.toml
> bump to 20.2.2

- docker/README.md
- docker/release/Dockerfile
> add docker image support.

- .ci-script/build-bin-for-linux-deploy.sh
- .ci-script/build-bin-for-mac-deploy.sh
- .ci-script/build-push-docker-image.sh
- .travis.yml
release and push image cita cli in travis ci
> release and push image cita cli in travis ci

- .ci-script/build-bin-for-linux-deploy.sh
- .ci-script/build-bin-for-mac-deploy.sh
- .ci-script/build-push-docker-image.sh
- .travis.yml
optimize release update tag obtain in travis and add note
> optimize release update tag obtain in travis and add note
